@startuml CU4 - Bloquear Días y Horarios

left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor #FFF1F2
    BorderColor #E11D48
    ArrowColor #BE123C
}

title CU4 - Bloquear días y horarios en calendario

actor "Secretaria" as SEC
actor "Médico" as MED

rectangle "Sistema de Turnos Médicos" {

    usecase "Bloquear días y\nhorarios en calendario" as CU4

    usecase "Seleccionar rango\nde fechas y horarios" as CU4_1
    usecase "Ingresar motivo\nu observación" as CU4_2
    usecase "Marcar horarios\ncomo no disponibles" as CU4_3

    CU4 ..> CU4_1       : <<include>>
    CU4 ..> CU4_2       : <<include>>
    CU4 ..> CU4_3       : <<include>>

}

MED --> CU4
SEC --> CU4

note right of CU4_2
  Posibles motivos:
  vacaciones, feriado,
  otra actividad
end note

note bottom of CU4_3
  En el calendario se visualiza
  el motivo del bloqueo en
  cada horario no disponible
end note

@enduml
