@startuml 01-solid-05-dip

skinparam classAttributeIconSize 0
title Principio de Inversión de Dependencias (DIP) - Basado en Tarjetas CRC

interface IGestorCitas {
    + registrarTurno(t: Turno)
    + cancelarTurno(id: int)
}

interface INotificador {
    + enviarRecordatorio(p: Paciente, mensaje: String)
}


class Recepcionista {
    - gestor: IGestorCitas
    + Recepcionista(gestor: IGestorCitas)
    + gestionarSolicitudPaciente()
}

class Agenda {
    - notificador: INotificador
    - turnos: List<Turno>
    + Agenda(notificador: INotificador)
    + procesarCita()
}

class Turno {
    - id: int
    - fecha: Date
}

class Paciente {
    - nombre: String
    - contacto: String
}

class NotificadorWhatsApp {
    + enviarRecordatorio(p: Paciente, mensaje: String)
}

Recepcionista --> IGestorCitas : "usa"
Agenda ..|> IGestorCitas : "realiza"
Agenda --> INotificador : "usa"
Agenda "1" *-- "*" Turno : "contiene"
NotificadorWhatsApp ..|> INotificador : "implementa"
Turno --> Paciente : "asignado a"

note bottom of Agenda
  Inyección de Dependencias:
  Agenda recibe el Notificador por constructor.
end note

@enduml