@startuml 01-solid-01-srp
skinparam classAttributeIconSize 0
title Principio de Responsabilidad Única (SRP)

class GestorPacientes {
    + registrarDatos(p: Paciente)
    + actualizarContacto(p: Paciente)
}

class GestorCitas {
    + asignarTurno(t: Turno)
    + cancelarTurno(id: int)
}

class Recepcionista {
    - gPacientes: GestorPacientes
    - gCitas: GestorCitas
    + atenderSolicitud()
}

Recepcionista --> GestorPacientes : "delega datos"
Recepcionista --> GestorCitas : "delega turnos"
@enduml