@startuml 01-solid-04-isp
skinparam classAttributeIconSize 0
title Principio de Segregación de Interfaces (ISP)

interface IGestionTurnos {
    + agendarCita()
    + cobrarTurno()
}

interface IConsultaMedica {
    + verHistoriaClinica()
    + emitirReceta()
}

class Recepcionista implements IGestionTurnos {
    + agendarCita()
    + cobrarTurno()
}

class Medico implements IConsultaMedica {
    + verHistoriaClinica()
    + emitirReceta()
}
@enduml