@startuml

skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
skinparam maxMessageSize 160
skinparam sequence {
    ArrowColor          #2C3E50
    LifeLineBorderColor #C0392B
    LifeLineBackgroundColor #FADBD8
    BoxBackgroundColor  #FDFEFE
    BoxBorderColor      #2C3E50
}
skinparam participant {
    BackgroundColor #FADBD8
    BorderColor     #C0392B
    FontColor       #1A252F
    FontStyle       bold
}
skinparam actor {
    BackgroundColor #FDEBD0
    BorderColor     #E67E22
    FontColor       #1A252F
    FontStyle       bold
}


title CU-02: Registrar Check-in\nFlujo Principal Exitoso

actor Secretaria

participant ":ControlSistema" as ControlSistema
participant ":Agenda" as Agenda
participant ":Turno" as Turno
participant ":LlegadaPaciente" as LlegadaPaciente

Secretaria -> ControlSistema : buscarTurnoPaciente(apellido,\nnombre, dni)
activate ControlSistema
ControlSistema -> Agenda : buscarTurnoPaciente(apellido,\nnombre, dni)

activate Agenda
Agenda -> Agenda : filtrarTurnosPorFechaActual(dni,\nfechaHoy)
Agenda --> ControlSistema : mostrarTurnoEncontrado
deactivate Agenda

ControlSistema --> Secretaria : mostrarTurnoEncontrado

Secretaria -> ControlSistema : seleccionarTurno(Turno)

ControlSistema -> Agenda : obtenerTurno(Turno)

activate Agenda
Agenda -> Turno : getEstado()
activate Turno
Turno --> Agenda : estado
deactivate Turno
Agenda --> ControlSistema : datosTurno
deactivate Agenda

ControlSistema --> Secretaria : habilitarRegistroPresencia

Secretaria -> ControlSistema : registrarPresencia(Turno)

ControlSistema -> Agenda : registrarPresencia(Turno)
deactivate ControlSistema
activate Agenda

create LlegadaPaciente
Agenda -> LlegadaPaciente : new(Turno,\nhoraLlegada)

activate LlegadaPaciente

Turno -> LlegadaPaciente : cambiarEstado("Presente")
activate Turno
LlegadaPaciente --> Turno : estadoActualizado
deactivate Turno
LlegadaPaciente -> LlegadaPaciente : actualizarPresencia(presente,\nestadoPresencia)
LlegadaPaciente -> Turno : registrarHoraLlegada
activate Turno
deactivate LlegadaPaciente
Turno --> Agenda : estadoActualizado
deactivate Turno
Agenda -> Agenda : cancelarRecordatoriosPendientes(Turno)
Agenda --> Agenda : recordatoriosCancelados()

Agenda --> ControlSistema : checkInRegistrado
activate ControlSistema

deactivate Agenda
ControlSistema --> Secretaria : confirmarCheckIn
deactivate ControlSistema

@enduml